config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get 'queries', to: 'queries#home'
  get :limbo, controller: 'queries'
  post :search, controller: 'queries'
  resources :users
  resources :recipes, only: %i[show create destroy]
  resource :dashboard, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes

  def disliked_recipes
    recipes.where(dislike: true).select('edamam_id').map(&:edamam_id).to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def show
    @favorites = current_user.recipes.where(dislike: false).order('name')
    @dislikes = current_user.recipes.where(dislike: true).order('name')
    @user = current_user
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def home
    @term = params[:q]
    @max = params[:max_cal]
    @health = params[:health]
    query = QueryResult.recent(params[:search_id])
    return unless query
    flash_errors(query)
    return unless query.hits
    @recipes = if signed_in?
                 query.filter_hits(current_user.disliked_recipes,
                                   query.hits).paginate(params[:page],
                                                        params[:anchor],
                                                        9)
               else
                 query.hits.paginate(params[:page], params[:anchor], 9)
               end
  end

  def index
    @term = params[:q]
    @max = params[:max_cal]
    @health = params[:health]
    query = QueryResult.recent(params[:search_id])
    return unless query
    flash_errors(query)
    return unless query.hits
    @recipes = if signed_in?
                 query.filter_hits(current_user.disliked_recipes,
                                   query.hits).paginate(params[:page],
                                                        params[:anchor],
                                                        9)
               else
                 query.hits.paginate(params[:page], params[:anchor], 9)
               end
  end

  def limbo
    render json: QueryResult.all_keys
  end

  def search
    QueryResult.remove(params[:old_id])
    new_recipes = api_call
    if empty_query?
      flash[:alert] = 'Oops! Looks like the search field was empty, please try again!'
    else
      store(new_recipes.search)
    end
    redirect_to queries_path(search_id: params[:search_id],
                             q: params[:q],
                             max_cal: params[:max_cal],
                             health: params[:health])
  end

  private

  def api_call
    GetRecipes.new(params[:q],
                   params[:max_cal],
                   params[:health])
  end

  def empty_query?
    /^\s*$/ =~ params[:q].to_s
  end

  def store(recipe_search)
    QueryResult.new(recipe_search,
                    params[:search_id])
  end

  def flash_errors(query)
    return flash.now[:notice] = 'API limit reached' if
      query.api_limit? || RecipeErrors.api_limit?
    return flash.now[:notice] = 'error' if query.query_error?
    return flash.now[:notice] = 'no recipe found' if query.no_recipe_found?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[create show destroy]
  
  def show
    recipe = current_recipe
    if recipe
      @recipe = recipe_dto_from_api(recipe)
      api_text = 'Oops! Looks like we are a bit busy...try again in a few minutes.'
      redirect_to queries_path, notice: api_text if RecipeErrors.api_limit?
    else
      redirect_to dashboard_path, status: :not_found
    end
  end

  def create
    Recipe.create(name: params[:recipe_name],
                  edamam_id: params[:id],
                  dislike: params[:dislike],
                  image: params[:image],
                  user_id: current_user.id)
  end

  def destroy
    recipe = current_recipe
    return render status: :forbidden if recipe.user_id != current_user.id
    recipe.destroy
  end

  private

  def current_recipe
    Recipe.find_by_id(params[:id])
  end

  def recipe_params
    params.permit(:name, :edamam_id, :dislike, :image)
  end

  def recipe_dto_from_api(recipe_data)
    recipe_call = GetRecipe.new(recipe_data.edamam_id)
    recipe = recipe_call.find_recipe
    RecipeErrors.store_api_result(recipe)
    RecipeErrors.api_limit? ? return : RecipeDto.new(recipe[0])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index; end

  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/queries_helper.rb
require 'securerandom'

module QueriesHelper
  def make_dto
    RecipeDto.new(self['recipe'])
  end

  def create_search_id
    SecureRandom.uuid
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def self.recipe_dto_from_api(recipe_data)
    recipe_call = GetRecipe.new(recipe_data.edamam_id)
    recipe = recipe_call.find_recipe
    RecipeErrors.store_api_result(recipe)
    RecipeErrors.api_limit? ? return : RecipeDto.new(recipe[0])
  end

  def self.percent_cals_from_fat(recipe)
    ((recipe.fat * 9) / recipe.calories) * 100
  end

  def self.percent_cals_from_protein(recipe)
    ((recipe.protein * 4) / recipe.calories) * 100
  end

  def self.percent_cals_from_carbs(recipe)
    ((recipe.carbs * 4) / recipe.calories) * 100
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dashboards/show.html.erb
<div class="row">
  <div class="small-12 medium-10 columns">
    <ul class="tabs" data-tabs id="example-tabs">
      <li class="tabs-title is-active">
        <a href="#panel1" aria-selected="true">Favorites</a>
      </li>
      <li class="tabs-title">
        <a data-tabs-target="panel2" href="#/tabs/panel2">Dislikes</a>
      </li>
      <li class="tabs-title">
        <a data-tabs-target="panel3" href="#/tabs/panel3">Manage Account</a>
      </li>
    </ul>
    <div class="tabs-content" data-tabs-content="example-tabs">
      <!-- TABS PANEL 1 BEGIN -->
      <div class="tabs-panel is-active" id="panel1">
        <h4 class='subheader text-center'>Favorites</h4>
        <div class="row">
          <% if @favorites.exists? %>
            <% @favorites.each.with_index do |fav, index| %>
              <div data-closable
                     class="dash callout small-12 medium-3 columns"
                     data-index='<%= index %>' >
                <div class="row">
                  <div class="small-12 columns">
                    <%= link_to image_tag(fav.image, class: 'dashboard-image',
                                             alt:'Recipe Photo'), 
                                             recipe_path(id: fav.id,
                                             search_id: params[:search_id]) %>
                  </div>
                  <div class="small-12 columns dash-close">
                    <%= button_to recipe_path(id: fav.id),
                                             class: 'dash-close-btn',
                                             'data-index' => index,
                                             method: :delete do %>
                      <i class="fa fas fa-times" aria-hidden="true"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <h6 class='text-center subheader'>
              Your favorite recipes will appear here
            </h6>
          <% end %>
        </div>
      </div>
      <!-- TABS PANEL 1 END -->
      <!-- TABS PANEL 2 BEGIN -->
      <div class="tabs-panel" id="panel2">
        <h4 class='subheader text-center'>Dislikes</h4>
        <div class="row">
          <% if @dislikes.exists? %>
            <% @dislikes.each.with_index do |dislike, index| %>
              <div data-closable
                   class="dash callout small-12 medium-3 columns"
                   data-index='<%= index %>' >
                <div class="row">
                  <div class="small-12 columns">
                    <%= image_tag(dislike.image, class: 'dashboard-image', alt:'Recipe Photo') %>
                  </div>
                  <div class="small-12 columns dash-close">
                    <%= button_to recipe_path(id: dislike.id),
                                              class: 'dash-close-btn',
                                              'data-index' => index,
                                              method: :delete do %>
                      <i class="fa fas fa-times" aria-hidden="true"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <h6 class='text-center subheader'>
              Recipes you have removed will appear here
            </h6>
          <% end %>
        </div>
      </div>
      <!-- TABS PANEL 2 END -->
      <!-- TABS PANEL 3 BEGIN -->
      <div class="tabs-panel" id="panel3">
        <div class='row'>
          <div class='dash-info small-12 columns'> <%= @user.email %></div>
          <div class='dash-info small-12 columns'>Member since <%= current_user.created_at.strftime("%B %d, %Y") %></div>
          <div class='dash-info small-12 columns'>Last logged in on <%=current_user.last_sign_in_at.strftime("%B %d, %Y") %></div>
          <div class='dash-info dash-btn small-12 columns'>
          <%= link_to "Edit Account",
              edit_user_registration_path(@user) %>
          </div>
          <div class="dash-info dash-btn small-12 columns">
            <%= link_to "Cancel My Account",
                registration_path(@user),
                data: { confirm: "Are you sure?" },
                method: :delete %>
          </div>
        </div>
      </div>
      <!-- TABS PANEL 3 END -->
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="title-bar">
  <div class="title-bar-left">
    <button class="menu-icon" type="button" data-open="offCanvas"></button>
    <span class="title-bar-title"><%= link_to image_tag('vegissimo.png'), root_path, class: "veg-logo" %></span>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="off-canvas position-left" id="offCanvas" data-off-canvas>
  <!-- Close button -->
  <button class="side-close-button" aria-label="Close menu" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
  <!-- Menu -->
  <ul class="vertical menu">
    <li>
      <%= link_to 'Home', root_path %>
    </li>
    <% if user_signed_in? %>
      <li>
        <%= link_to 'Dashboard', dashboard_path(search_id: params[:search_id]) %>
      </li>
      <li>
        <%= link_to 'Sign out', destroy_user_session_path(search_id: params[:search_id]), method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Sign in', new_user_session_path(search_id: params[:search_id]) %>
      </li>
      <li>
        <%= link_to 'Sign up', new_user_registration_path(search_id: params[:search_id]) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-123138750-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-123138750-1');
    </script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Vegissimo" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/fb33a1c2bd.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/sidebar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/queries/_buttons.html.erb
<div class="button-row-container">
  <div class="row btn-row">
    <% if current_user %>
      <div id="change-favorites-<%=recipe.e_id %>" class="like-btns">
        <% if Recipe.exists?(edamam_id: recipe.e_id, dislike: false) %>
          <%= link_to dashboard_path(search_id: params[:search_id]),
                      class: 'round-btn favorite-btn',
                      data: { button_id: recipe.e_id },
                      method: :get do %>
            <i class="fa fa-heart"></i>
          <% end %>
        <% elsif Recipe.exists?(edamam_id: recipe.e_id, dislike: true) %>
          <%= link_to dashboard_path(search_id: params[:search_id]),
                      class: 'round-btn dislike-btn',
                      data: { button_id: recipe.e_id },
                      method: :get do %>
            <i class="fa fa-thumbs-down"></i>
          <% end %>
        <% else %>
          <%= button_to recipes_path(user_id: current_user.id,
                                      id: recipe.e_id,
                                      recipe_name: recipe.label,
                                      dislike: false,
                                      image: recipe.image ),
                                      class: 'round-btn clean-btn favorite',
                                      data: { button_id: recipe.e_id },
                                      method: :post do %>
            <i class="fa fa-heart-o"></i>
          <% end %>
          <%= button_to recipes_path(user_id: current_user.id,
                                        id: recipe.e_id,
                                        recipe_name: recipe.label,
                                        dislike: true,
                                        image: recipe.image ),
                                        class: 'round-btn clean-btn dislike',
                                        data: { button_id: recipe.e_id },
                                        method: :post do %>
            <i class="fa fa-thumbs-o-down"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="small-3 social">
    <%= social_share_button_tag("Vegissimo") %>
    </div>
  </div>
</div>

app/views/queries/_recipe_cards.html.erb
<% @recipes.each.with_index do |recipe, index| %>
  <% recipe = recipe.make_dto %>
  <div class="recipe-card callout callout-hover-reveal">
    <div class="callout-body">
      <div class="row align-center">
        <div class="column text-center">
          <h5><%= recipe.label %></h5>
          <div class="card-image">
            <%= image_tag(recipe.image) %>
          </div>
          <%= render partial: 'buttons', locals: { recipe: recipe } %>
          <div class="row align-center">
            <div class="column">
              <span class="label">
                <b><%= recipe.yield %></b>
                servings
              </span>
            </div>
            <div class="column">
              <span class="label">
                <b><%= (recipe.calories/recipe.yield).round(1)%></b>
                calories per serving
              </span>
            </div>
          </div>
          <div class="pointer text-center" data-index='<%= index %>' >
            <i class="fa fa-chevron-down"></i>
          </div>
        </div>
      </div>
    </div>
      <div class="callout-footer" data-index='<%= index %>' >
        <div class="row align-center">
          <div class="column text-center">
              <h4>Ingredients</h4>
          </div>
        </div>
        <div class="row align-center">
          <div class="column">
            <ul class='list-group'>
              <% recipe.ingredient_list.each do |ingred| %>
                <li class='list-item'>
                  <%= ingred %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <br>
        <div class="row align-center">
          <div class="column text-center">
            <%= link_to 'See Directions',
                        recipe.url,
                        target: '_blank',
                        class:'button',
                        method: :get %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/queries/_search_form.html.erb
<div class="row">
  <div class="small-8 columns">
    <%= form_tag(search_path, :method=>'post', class:'search-form') do %>
    <%= hidden_field_tag('old_id', params[:search_id]) %>
    <%= hidden_field_tag('search_id', create_search_id) %>
    <div class="row text-centered">
      <div class="small-12 columns filters" >
        <i class="fa fa-filter search-filter-results"><span class="filter-results-text">filter results</span></i>
      </div>
      <!-- Filter Box Begin -->
      <div id="searchFilters">
        <div class="small-12 columns">
          <div class='search-description'>Dietary Choice</div>
        </div>
        <!-- Radio Inputs Begin -->
        <div class="small-12 columns radio-inputs">
          <%= radio_button_tag(:health,
                                "vegan",
                                 @health == 'vegetarian' ? false : true) %>
          <%= label :health_vegan, 'vegan', class: 'radio-label' %>
          <%= radio_button_tag(:health,
                                 "vegetarian",
                                @health == 'vegetarian' ? true : false) %>
          <%= label :health_vegetarian, 'vegetarian', class: 'radio-label' %>
        </div>
        <!-- Radio Inputs End -->
        <!-- Max Calories Begin -->
        <div class="small-12 columns">
          <div class='search-description'>Calories Per Serving</div>
        </div>
        
        <div class="row">
          <div class="column">
            <div class="input-group">
              <div class="input-group-button">
                <button type="button"
                        class="cal-btn"
                        data-quantity="minus"
                        data-field="max_cal">
                  <i class="fa fas fa-caret-left" aria-hidden="true"></i>
                </button>
              </div>
              <%= number_field_tag "max_cal",
                                   params[:max_cal] ? params[:max_cal] : 500,
                                   min:1,
                                   required: true,
                                   class: 'input-group-field' %>
              <div class="input-group-button">
                <button type="button"
                        class="cal-btn"
                        data-quantity="plus"
                        data-field="max_cal">
                  <i class="fa fas fa-caret-right" aria-hidden="true"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- Max Calories End -->
      </div>
      <!-- Filter Box End -->
      <!-- Search Bar Begin -->
      <div class="search-box-field">
        <div class="row">
          <div class="small-8 columns">
            <%= text_field_tag "q",
              @term,
              maxlength: 50,
              placeholder: 'avocado',
              required: true,
              class: 'text-input' %>
          </div>
          <div class="small-4 columns">
            <%= button_tag(type:'submit', class:'submit-btn float-right') do %>
              <i class="fa fa-search"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <!-- Search Bar End -->
    <% end %>
  </div>
</div>

app/views/queries/home.html.erb
<div class="row" id="list-recipe-results">
  <% if @recipes %>
    <% @recipes.each.with_index do |recipe, index| %>
    <% recipe = recipe.make_dto %>
      <div class="small-12 medium-3 columns card">
        <%= image_tag(recipe.image) %>
        <%= render partial: 'buttons', locals: { recipe: recipe } %>
        <div class="card-section">
          <p><%= recipe.label %><br><span id="source-text"> (<%= recipe.source %>)</span></p>
          <span class="label">
            <b><%= recipe.yield.round %></b>
            servings
          </span><br>
          <span class="label">
            <b><%= (recipe.calories/recipe.yield).round %></b>
            calories per serving
          </span>
        </div>
        <div class="pointer text-center" data-index='<%= index %>' >
          <i class="fa fa-chevron-down"></i>
        </div>
        
        <div class="callout-footer" data-index='<%= index %>'>
          
          <div class="row align-center">
            <div class="column text-center">
              <h4>Ingredients</h4>
            </div>
          </div>
          
          <div class="row align-center">
            <div class="column">
              <ul class='list-group'>
                <% recipe.ingredient_list.each do |ingred| %>
                  <li class='list-item'>
                    <%= ingred %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
          
          <br>
          
          <div class="row align-center">
            <div class="column text-center card-btn">
              <%= link_to 'See Directions',
                          recipe.url,
                          target: '_blank',
                          class:'button',
                          method: :get %>
            </div>
          </div>
          <div class="pointer text-center" data-index='<%= index %>' >
            <i class="fa fa-chevron-up"></i>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="small-12 columns text-center">
  <%= will_paginate @recipes,
                    params: {anchor: 'cards'},
                    inner_window: 1,
                    outer_window: 0,
                    previous_label: '<',
                    next_label: '>'%>
</div>

app/views/recipes/show.html.erb
<%= image_tag(@recipe.image) %>
<br /><br />
<%= @recipe.label %>
<% if Recipe.exists?(edamam_id: @recipe.e_id, dislike: true) %>
<i class="fa fa-thumbs-down"></i>
<% else %>
  <i class="fa fa-heart"></i>
<% end %>
<br /><br />
Servings: <%= @recipe.yield %>
<br />
NUTRION PER SERVING:<br /><br />
Calories: <%= (@recipe.calories/@recipe.yield).round %><br />
Fat: <%= (@recipe.fat/@recipe.yield).round %><br />
Carbohydrates: <%= (@recipe.carbs/@recipe.yield).round %><br />
Protein: <%= (@recipe.protein/@recipe.yield).round %>
<br /><br />

<div id="chart" data-fat-cals="<%= RecipesHelper.percent_cals_from_fat(@recipe) %>"
  data-protein-cals="<%= RecipesHelper.percent_cals_from_protein(@recipe) %>"
  data-carbs-cals="<%= RecipesHelper.percent_cals_from_carbs(@recipe) %>">
  <canvas id="macrosChart" ></canvas>
  <p id="caption">Note: Due to the nutrient amounts being rounded before our
    calculations, percentages may not add to exactly 100. </p>
</div>

<br /><br /><br />

Ingredients:
<% @recipe.ingredient_list.each do |ingredient| %>
  <br />
  <%= ingredient %>
<% end %>
<br /><br />
<%= link_to 'Make Recipe', @recipe.url, target: '_blank', class: 'button', method: :get %>

app/views/static_pages/index.html.erb
<div class="hero-section">
  <div class="hero">
    <div class="row align-center">
      <div class="small-12 medium-8 columns hero-column">
        <div class="search-box">
          <h1 class="search-title">Find Recipes</h1>
          <%= render 'queries/search_form' %>
        </div>
      </div>
    </div>
  </div>
</div>